### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by hkvaka** [BiologyTools/BioGTK#3]
Hi

I am trying to install the BioGtk package and getting the following error with one of the dependency

NU1102: Unable to find package AForgeBio with version (>= 1.2.0)
  - Found 1 version(s) in nuget.org [ Nearest version: 1.1.0 ]

![image](https://user-images.githubusercontent.com/118275347/221790392-22a699e5-7cb7-4121-9c74-719e8a61b0db.png)

**Comment by BiologyTools** [comment]
Yes you need to add the AForgeBio the version of the AForge library used by BioGTK. By adding the package https://www.nuget.org/packages/AForgeBio/ or project https://github.com/BiologyTools/AForgeBio

**Comment by hkvaka** [comment]
Thankyou for a quick reply

It appears that the BioGTK expects Aforge Library >= 1.2.0 but the Aforge library on nuget is only 1.1.0 

tries installing the Aforge 1.1.0 and then re install the BioGTK package and getting the following error

![image](https://user-images.githubusercontent.com/118275347/221795279-e91f523d-c050-4eee-80cc-9a987da734a2.png)

**Comment by BiologyTools** [comment]
I have uploaded the latest version of the package AForgeBio 1.2.0. https://www.nuget.org/packages/AForgeBio/ and BioGTK 2.4 https://www.nuget.org/packages/BioGTK/2.4.0 Hopefully this will fix the isssue.

**Comment by hkvaka** [comment]
Many Thanks for quickly fixing this

I can now install the package
